server:
  port: 8083

spring:
  application:
    name: file-service

file:
  storage:
    path: ./uploads

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
